// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJJg3E9DkgTuEXzDgZWM86-54py8s78VA',
    appId: '1:1098324065631:web:9d3fb1986e06faf2a3caea',
    messagingSenderId: '1098324065631',
    projectId: 'login-9f852',
    authDomain: 'login-9f852.firebaseapp.com',
    storageBucket: 'login-9f852.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhjCxuDezbYmBtTkaN_0akKWnPZdt-krU',
    appId: '1:1098324065631:android:3512fec33dfcdcf3a3caea',
    messagingSenderId: '1098324065631',
    projectId: 'login-9f852',
    storageBucket: 'login-9f852.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKyLx-ObS5B6n2mWVTmQgCDWSQqPctJQE',
    appId: '1:1098324065631:ios:b621a9384e451c13a3caea',
    messagingSenderId: '1098324065631',
    projectId: 'login-9f852',
    storageBucket: 'login-9f852.appspot.com',
    iosBundleId: 'com.example.recipesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKyLx-ObS5B6n2mWVTmQgCDWSQqPctJQE',
    appId: '1:1098324065631:ios:fbfb45770b98eef8a3caea',
    messagingSenderId: '1098324065631',
    projectId: 'login-9f852',
    storageBucket: 'login-9f852.appspot.com',
    iosBundleId: 'com.example.recipesApp.RunnerTests',
  );
}
